@startuml
actor Paciente
actor Médico
actor Recepcionista
actor Administrador

Paciente -- (Agendar Consulta)
Paciente -- (Cancelar Consulta)
Paciente -- (Visualizar Consulta)	

Médico -- (Visualizar Agenda)

Recepcionista -- (Cadastrar Paciente)
Recepcionista -- (Agendar Consulta)
Recepcionista -- (Cancelar Consulta)
Recepcionista -- (Atualizar Consulta)
Recepcionista -- (Visualizar Agenda)

Administrador -- (Cadastrar Médico)
Administrador -- (Gerar Relatórios)

@enduml


@startuml

class Paciente {
  +int Id
  +String Nome
  +Date DataNascimento
  +String Contato
  +String Endereco
  +void CadastrarPaciente()
  +void AtualizarPaciente()
  +void RemoverPaciente()
}

class Medico {
  +int Id
  +String Nome
  +String Especialidade
  +String CRM
  +String Contato
  +List<Horario> HorariosAtendimento
  +void CadastrarMedico()
  +void AtualizarMedico()
  +void RemoverMedico()
}

class Consulta {
  +int Id
  +Date Data
  +Time Hora
  +String Observacoes
  +void AgendarConsulta()
  +void AtualizarConsulta()
  +void CancelarConsulta()
}

class Horario {
  +int Id
  +String DiaSemana
  +Time HoraInicio
  +Time HoraFim
}

class Agenda {
  +List<Consulta> Consultas
  +void VisualizarAgenda()
}

class Relatorio {
  +void GerarRelatorioConsultasRealizadas(Date inicio, Date fim)
  +void GerarRelatorioConsultasCanceladas(Date inicio, Date fim)
  +void GerarRelatorioConsultasAgendadas(Date inicio, Date fim)
}

Paciente "1" -- "0..*" Consulta : agenda
Medico "1" -- "0..*" Consulta : realiza
Medico "1" -- "0..*" Horario : possui
Consulta "0..*" -- "1" Agenda : agenda
Consulta "1" -- "1" Paciente : possui
Consulta "1" -- "1" Medico : possui
Agenda "1" -- "1" Medico : pertence
Relatorio "1" -- "1" Administrador : gera

@enduml